Convert bash scripts to fish

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,86 +1,79 @@
-#!/usr/bin/env bash
+#!/usr/bin/env fish
 
-set -euo pipefail
+function main
+    stow_config
+    configure_homebrew
+    update_homebrew
+    generate_homebrew_bundle
+    install_homebrew_bundle
+    run_install_scripts
+    log_success "Finished"
+end
 
-main() {
-  stow_config
-  configure_homebrew
-  update_homebrew
-  generate_homebrew_bundle
-  install_homebrew_bundle
-  run_install_scripts
-  log_success "Finished"
-}
+function stow_config
+    log_step "Stow config"
 
-stow_config() {
-  log_step "Stow config"
-  stow --target "$HOME" --ignore Brewfile stow # configure stow first
-  for package in */
-  do
-    stow --target "$HOME" "$package"
-  done
-}
+    # Configure stow first
+    stow --target $HOME --ignore Brewfile stow
+    or fail
 
-configure_homebrew() {
-  export HOMEBREW_NO_ENV_HINTS=1
-  export HOMEBREW_NO_ANALYTICS=1
-  export HOMEBREW_NO_INSECURE_REDIRECT=1
-}
+    for package in */
+        stow --target $HOME $package
+        or fail
+    end
+end
 
-update_homebrew() {
-  log_step "Update Homebrew"
-  brew update
-}
+function configure_homebrew
+    set -gx HOMEBREW_NO_ENV_HINTS 1
+    set -gx HOMEBREW_NO_ANALYTICS 1
+    set -gx HOMEBREW_NO_INSECURE_REDIRECT 1
+end
 
-generate_homebrew_bundle() {
-  log_step "Generate Homebrew bundle"
-  "$HOME/bin/generate-homebrew-bundle"
-}
+function update_homebrew
+    log_step "Update Homebrew"
+    brew update
+    or fail
+end
 
-install_homebrew_bundle() {
-  log_step "Check Homebrew bundle"
-  if ! brew bundle check --global --verbose
-  then
-    log_step "Install Homebrew bundle"
-    brew bundle install --global
-  fi
-}
+function generate_homebrew_bundle
+    log_step "Generate Homebrew bundle"
+    $HOME/bin/generate-homebrew-bundle
+    or fail
+end
 
-run_install_scripts() {
-  shopt -s globstar nullglob
-  for installer in */install
-  do
-    log_step "Install $(dirname "$installer")"
-    # shellcheck disable=SC1090
-    "$installer"
-  done
-}
+function install_homebrew_bundle
+    log_step "Check Homebrew bundle"
+    if not brew bundle check --global --verbose
+        log_step "Install Homebrew bundle"
+        brew bundle install --global
+        or fail
+    end
+end
 
-terminate() {
-  local exit_code=$?
-  if [ $exit_code -gt 0 ]
-  then
-    log_error "Error (exit code ${exit_code})"
-  fi
-}
+function run_install_scripts
+    for installer in */install
+        log_step "Install "(dirname $installer)
+        $installer
+        or fail
+    end
+end
 
-log_step() {
-  local message=$1
-  echo -e "\033[1m──→ ${message}\033[0m"
-}
+function fail
+    log_error "Failed"
+    exit 1
+end
 
-log_success() {
-  local message=$1
-  echo -e "\033[1;32m──→ ${message}\033[0m"
-}
+function log_step
+    echo -e "\033[1m──→ $argv[1]\033[0m"
+end
 
-log_error() {
-  local message=$1
-  echo -e "\033[1;31m──X ${message}\033[0m"
-}
+function log_success
+    echo -e "\033[1;32m──→ $argv[1]\033[0m"
+end
 
-(
-  trap terminate EXIT
-  cd "$HOME/.dotfiles/"
-  main
-)
+function log_error
+    echo -e "\033[1;31m──X $argv[1]\033[0m"
+end
+
+cd $HOME/.dotfiles/
+main
